# To create the conda environment, run:
#   conda env create -f environment.yml
name: multi-agent
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.13.3
  - python-dotenv=1.1.0
  - langchain=0.3.25
  - matplotlib=3.10.0
  - pip
  - pip:
      - langgraph==0.4.7
      - langchain_openai==0.3.18
      - "-e ."
